# Generated by Django 5.0.10 on 2025-04-10 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Description', models.CharField(max_length=500)),
                ('Availability', models.IntegerField()),
                ('Stock', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Sub_Category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhsapp.subcategory')),
            ],
        ),
    ]
