# Generated by Django 5.0.10 on 2025-04-10 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='variation_option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('color_code', models.CharField(max_length=100)),
                ('variation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhsapp.variation')),
            ],
        ),
    ]
