# Generated by Django 5.0.10 on 2025-04-11 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhsapp', '0002_product'),
        ('mhsapp', '0002_variation_variation_option'),
    ]

    operations = [
    ]
