# Generated by Django 5.0.10 on 2025-04-11 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhsapp', '0003_merge_0002_product_0002_variation_variation_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhsapp.product')),
                ('option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhsapp.variation_option')),
            ],
        ),
    ]
