<<<<<<< HEAD
# Generated by Django 5.0.10 on 2025-04-14 16:48
=======
# Generated by Django 5.0.10 on 2025-04-14 07:03
>>>>>>> 10f1f89895ef207a968323dc582db7fb2c83f83a

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhsapp', '0004_product_variation'),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('product_variation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhsapp.product_variation')),
=======
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Product_variation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhsapp.product_variation')),
>>>>>>> 10f1f89895ef207a968323dc582db7fb2c83f83a
            ],
        ),
    ]
