# Generated by Django 5.0.10 on 2025-04-14 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhsapp', '0004_product_variation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('product_variation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhsapp.product_variation')),
            ],
        ),
    ]
