# Generated by Django 5.0.10 on 2025-04-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhsapp', '0005_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_path',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
