# Generated by Django 5.0.10 on 2025-04-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhsapp', '0006_alter_image_img_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_path',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
