# Generated by Django 5.0.10 on 2025-04-18 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhsapp', '0008_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Customer_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mhsapp.customer'),
        ),
    ]
